### ISSUE TITLE
Do you need help on web design?

### ISSUE THREAD

**Issue by altbdoor** [TrainStream/trainstream.github.io#1]
Hi, do you need assistance in web design on the website for trainstream? We can discuss on how you want the website to look like, and I can try to draft some designs. But if you prefer to maintain the current aesthetic, that is fine too. Cheers!

**Comment by TrainStream** [comment]
Are you still alive and interested? Assuming you are somebody that wants to do it for the train/stream love and not just searching for a random job?


> 
> 
> Hi, do you need assistance in web design on the website for trainstream? We can discuss on how you want the website to look like, and I can try to draft some designs. But if you prefer to maintain the current aesthetic, that is fine too. Cheers!

**Comment by altbdoor** [comment]
Hello there 👋 Its been three years!

Yes, my offer still stands! I could help make the site a little better here and there, and I will not seek any form of payment, nor will this be a job. Its just something I do out of my free time, for open source here and there.

I found your comment in /jp/ (I think?), and I probably cannot help much in terms of keeping the content here up to date, since I have not visited /jp/ that often. Best I could do is probably make the work on updating the site content a little easier.

**Comment by TrainStream** [comment]
Thank you for the interest in helping out. An easier way to update might definitely be helpful. It is not exactly hard now either, but I am sure a more sophisticated system can be made. Actually I just didn't see your post here until now. Plus it is has been only two years and a bit. Is there any way I can contact you? By email (the one in your profile?) and them maybe by something else maybe?
