### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by githubuser537** [TrainStream/trainstream.github.io#3]
I'm guessing this is how to contact you. So what do I do and how do I do it? I literally just joined github 3 hours ago so know nothing of how it works, so please give as much detail as you can (including what you do and don't want added to your website).

**Comment by TrainStream** [comment]
Sure, this works. I guess there was no PMing. Any contacts that I can have? Irc, discord, skype, anything? Or if you want first give me an email to write to and them send me that info.

**Comment by githubuser537** [comment]
githubuser537 @ mail.com remove the spaces
